spring:
  profiles:
    actives:
    - dev
---
spring:
  profiles: dev
  application:
    name:microservicecloud-config-kjq-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-kjq-test